#ansible-playbook block_rescue.yml --skip-tags=bad 
#ansible-playbook block_rescue.yml --skip-tags=bad_rescue
- hosts: localhost
  gather_facts: false
  pre_tasks:
    - ansible.builtin.debug:
        msg: "Task in pretask block"
      ## Here you can delegate jobs somewhere
      delegate_to: 127.0.0.1
  ## Here goes main block
  tasks:
    ## You can execute tasks by blocks
    - name: Unsolicited upgrade
      block:
    ## Scripts are in /files directory, if exit non zero task failed
        - script: bad_checker.sh
          delegate_to: localhost
          tags: bad

        - ansible.builtin.debug:
            msg: "Second task in tasks block"
      rescue:
    ## Block run ALWAYS if something went wrong
        - ansible.builtin.debug:
            msg: "Task in rescue block"
        - script: good_checker.sh
          delegate_to: localhost
          tags: good
        - script: bad_checker.sh
          delegate_to: localhost
          tags: bad_rescue
      always:
        - ansible.builtin.debug:
            msg: "Task in always block"
      # The always section runs regardless of the results of the block and rescue sections.
  
  post_tasks:
  ## post tasks will be executed if tasks been successuly done
  ## in our case if rescue suceed you will get message
    - name: Send notify to Telegram
      community.general.telegram:
        token: "{{telegram_token}}"
        api_args:
          chat_id: "{{telegram_chat_id}}"
          parse_mode: "markdown"
          text: |
              "Ansible task surprisingly went well"
          disable_web_page_preview: true
          disable_notification: false