- name: Notify telegram
  hosts: localhost
  tasks:

    - name: Send notify to Telegram
      community.general.telegram:
        token: "{{telegram_token}}"
        api_args:
          chat_id: "{{telegram_chat_id}}"
          parse_mode: "markdown"
          text: |
            "Ansible task finished"
            ## Test
          disable_web_page_preview: true
          disable_notification: false